### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dotnize** [mugnavo/startupsphere-frontend#31]
priority

- [x] 1. display report content in modal (using `.content` field formatted like a csv file)
- [x] 2. more specific names for reports (e.g. add which filters were selected), or let user specify?
- [x] 3. fix display of investor details (some of them were moved to user's details) based on recent InvestTrack changes
- [x] 4. hover card on map
  ![image](https://github.com/user-attachments/assets/d7c3c052-ad3a-4ff6-87ee-50832ba2cf02)
- [ ] 5. fix and clarify data for analytics

optional, depending on startupvest

- [ ] multiple selectable categories
